In [1]:
import yfinance as yf
import pandas as pd

In [2]:
tickers = ["AAPL", "AMZN", "GOOG", "MSFT", "NVDA", "^GSPC"]
start_date = '1994-01-01'
end_date = '2024-03-31'

In [3]:
data = {}
for ticker in tickers:
    data[ticker] = yf.download(ticker, start=start_date, end=end_date, interval="1d")

[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed

In [7]:
data

{'AAPL':                   Open        High         Low       Close   Adj Close  \
 Date
 1994-01-03    0.263393    0.267857    0.258929    0.266741    0.219874
 1994-01-04    0.270089    0.281250    0.267857    0.281250    0.231834
 1994-01-05    0.283482    0.302455    0.283482    0.301339    0.248393
 1994-01-06    0.301339    0.303571    0.290179    0.292411    0.241034
 1994-01-07    0.285714    0.296875    0.279018    0.295759    0.243794
 ...                ...         ...         ...         ...         ...
 2024-03-22  171.759995  173.050003  170.059998  172.279999  172.046646
 2024-03-25  170.570007  171.940002  169.449997  170.850006  170.618591
 2024-03-26  170.000000  171.419998  169.580002  169.710007  169.480133
 2024-03-27  170.410004  173.600006  170.110001  173.309998  173.075241
 2024-03-28  171.750000  172.229996  170.509995  171.479996  171.247726

                Volume
 Date
 1994-01-03  181529600
 1994-01-04  285174400
 1994-01-05  612136000
 1994-01-06  366508800
 1994-01-07  298793600
 ...               ...
 2024-03-22   71106600
 2024-03-25   54288300
 2024-03-26   57388400
 2024-03-27   60273300
 2024-03-28   65672700

 [7613 rows x 6 columns],
 'AMZN':                   Open        High         Low       Close   Adj Close  \
 Date
 1997-05-15    0.121875    0.125000    0.096354    0.097917    0.097917
 1997-05-16    0.098438    0.098958    0.085417    0.086458    0.086458
 1997-05-19    0.088021    0.088542    0.081250    0.085417    0.085417
 1997-05-20    0.086458    0.087500    0.081771    0.081771    0.081771
 1997-05-21    0.081771    0.082292    0.068750    0.071354    0.071354
 ...                ...         ...         ...         ...         ...
 2024-03-22  177.750000  179.259995  176.750000  178.869995  178.869995
 2024-03-25  178.009995  180.990005  177.240005  179.710007  179.710007
 2024-03-26  180.149994  180.449997  177.949997  178.300003  178.300003
 2024-03-27  179.880005  180.000000  177.309998  179.830002  179.830002
 2024-03-28  180.169998  181.699997  179.259995  180.380005  180.380005

                 Volume
 Date
 1997-05-15  1443120000
 1997-05-16   294000000
 1997-05-19   122136000
 1997-05-20   109344000
 1997-05-21   377064000
 ...                ...
 2024-03-22    27964100
 2024-03-25    29815500
 2024-03-26    29659000
 2024-03-27    33272600
 2024-03-28    38051600

 [6762 rows x 6 columns],
 'GOOG':                   Open        High         Low       Close   Adj Close  \
 Date
 2004-08-19    2.490664    2.591785    2.390042    2.499133    2.496292
 2004-08-20    2.515820    2.716817    2.503118    2.697639    2.694573
 2004-08-23    2.758411    2.826406    2.716070    2.724787    2.721690
 2004-08-24    2.770615    2.779581    2.579581    2.611960    2.608991
 2004-08-25    2.614201    2.689918    2.587302    2.640104    2.637103
 ...                ...         ...         ...         ...         ...
 2024-03-22  150.240005  152.559998  150.089996  151.770004  151.597488
 2024-03-25  150.949997  151.455994  148.800003  151.149994  150.978195
 2024-03-26  151.240005  153.199997  151.029999  151.699997  151.527573
 2024-03-27  152.145004  152.690002  150.130005  151.940002  151.767303
 2024-03-28  152.000000  152.669998  151.330002  152.259995  152.086929

                Volume
 Date
 2004-08-19  897427216
 2004-08-20  458857488
 2004-08-23  366857939
 2004-08-24  306396159
 2004-08-25  184645512
 ...               ...
 2024-03-22   19226300
 2024-03-25   15114700
 2024-03-26   19312700
 2024-03-27   16622000
 2024-03-28   21105600

 [4936 rows x 6 columns],
 'MSFT':                   Open        High         Low       Close   Adj Close  \
 Date
 1994-01-03    2.515625    2.523438    2.476563    2.503906    1.546676
 1994-01-04    2.507813    2.523438    2.476563    2.515625    1.553915
 1994-01-05    2.507813    2.578125    2.500000    2.570313    1.587696
 1994-01-06    2.582031    2.648438    2.578125    2.644531    1.633541
 1994-01-07    2.632813    2.679688    2.601563    2.664063    1.645605
 ...                ...         ...         ...         ...         ...
 2024-03-22  429.700012  429.859985  426.070007  428.739990  427.968048
 2024-03-25  425.239990  427.410004  421.609985  422.859985  422.098633
 2024-03-26  425.609985  425.989990  421.350006  421.649994  420.890808
 2024-03-27  424.440002  424.450012  419.010010  421.429993  420.671204
 2024-03-28  420.959991  421.869995  419.119995  420.720001  419.962494

               Volume
 Date
 1994-01-03  36646400
 1994-01-04  45302400
 1994-01-05  53974400
 1994-01-06  82006400
 1994-01-07  70832000
 ...              ...
 2024-03-22  17636500
 2024-03-25  18060500
 2024-03-26  16725600
 2024-03-27  16705000
 2024-03-28  21871200

 [7613 rows x 6 columns],
 'NVDA':                  Open       High        Low      Close  Adj Close      Volume
 Date
 1999-01-22   0.043750   0.048828   0.038802   0.041016   0.037621  2714688000
 1999-01-25   0.044271   0.045833   0.041016   0.045313   0.041562   510480000
 1999-01-26   0.045833   0.046745   0.041146   0.041797   0.038337   343200000
 1999-01-27   0.041927   0.042969   0.039583   0.041667   0.038218   244368000
 1999-01-28   0.041667   0.041927   0.041276   0.041536   0.038098   227520000
 ...               ...        ...        ...        ...        ...         ...
 2024-03-22  91.140999  94.778000  90.834000  94.289001  94.281258   586719000
 2024-03-25  93.941002  96.765999  93.510002  95.001999  94.994194   552136000
 2024-03-26  95.850998  96.375000  92.501999  92.560997  92.553398   513648000
 2024-03-27  93.112000  93.239998  89.123001  90.250000  90.242584   586067000
 2024-03-28  90.000000  91.300003  89.193001  90.356003  90.348579   435212000

 [6337 rows x 6 columns],
 '^GSPC':                    Open         High          Low        Close    Adj Close  \
 Date
 1994-01-03   466.510010   466.940002   464.359985   465.440002   465.440002
 1994-01-04   465.440002   466.890015   464.440002   466.890015   466.890015
 1994-01-05   466.890015   467.820007   465.920013   467.549988   467.549988
 1994-01-06   467.549988   469.000000   467.019989   467.119995   467.119995
 1994-01-07   467.089996   470.260010   467.029999   469.899994   469.899994
 ...                 ...          ...          ...          ...          ...
 2024-03-22  5242.479980  5246.089844  5229.870117  5234.180176  5234.180176
 2024-03-25  5219.520020  5229.089844  5216.089844  5218.189941  5218.189941
 2024-03-26  5228.850098  5235.160156  5203.419922  5203.580078  5203.580078
 2024-03-27  5226.310059  5249.259766  5213.919922  5248.490234  5248.490234
 2024-03-28  5248.029785  5264.850098  5245.819824  5254.350098  5254.350098

                 Volume
 Date
 1994-01-03   270140000
 1994-01-04   326600000
 1994-01-05   400030000
 1994-01-06   365960000
 1994-01-07   324920000
 ...                ...
 2024-03-22  3374700000
 2024-03-25  3331360000
 2024-03-26  3871790000
 2024-03-27  3850500000
 2024-03-28  3998270000

 [7613 rows x 6 columns]}

In [9]:
# save to csv
timestamp = pd.Timestamp.now().strftime("%Y-%m-%d-%H-%M")
# file_name = f'{ticker}_{timestamp}.csv'
for ticker in tickers:
    file_name = f'{ticker}.csv'
    file_path = f'./data/stocks/{file_name}'
    data[ticker].to_csv(file_path)